

```{r}
load("/home/mae5755.16/Downloads/aula11/EX1_dois_fatores.RData")
```


```{r}
load("/home/mae5755.16/Downloads/aula11/script_anova_dois_fatores.R")
```

```{r}
load("/home/mae5755.16/Downloads/aula11/EX1_dois_fatores.RData")
```


```{r}
Dataset <- readXL("/home/mae5755.16/Downloads/aula11/Espirometria.xlsx", rownames=FALSE, header=TRUE, na="", 
  sheet="Espirometria_curso", stringsAsFactors=TRUE)
```

```{r}
Dataset <- within(Dataset, {
  exposicao <- as.factor(exposicao)
})
```

```{r}
with(Dataset, tapply(cvfpred, exposicao, median, na.rm=TRUE))
kruskal.test(cvfpred ~ exposicao, data=Dataset)
```

```{r}
library(mvtnorm, pos=14)
```


```{r}
library(survival, pos=14)
```


```{r}
library(MASS, pos=14)
```


```{r}
library(TH.data, pos=14)
```


```{r}
library(multcomp, pos=14)
```


```{r}
library(abind, pos=19)
```


```{r}
AnovaModel.1 <- aov(temtraba ~ exposicao, data=Dataset)
summary(AnovaModel.1)
with(Dataset, numSummary(temtraba, groups=exposicao, statistics=c("mean", "sd")))
```

```{r}
with(Dataset, tapply(temtraba, exposicao, median, na.rm=TRUE))
kruskal.test(temtraba ~ exposicao, data=Dataset)
```

```{r}
load("/home/mae5755.16/Downloads/aula11/PulsacaoUCLAD1.RData")
```

```{r}
Dataset <- readXL("/home/mae5755.16/Downloads/aula11/Espirometria.xlsx", rownames=FALSE, header=TRUE, na="", 
  sheet="Espirometria_curso", stringsAsFactors=TRUE)
```


```{r}
Dataset <- within(Dataset, {
  exposicao <- as.factor(exposicao)
})
```


```{r}
with(Dataset, tapply(cvfpred, exposicao, median, na.rm=TRUE))
```


```{r}
kruskal.test(cvfpred ~ exposicao, data=Dataset)
```


```{r}
library(mvtnorm, pos=14)
```


```{r}
library(survival, pos=14)
```


```{r}
library(MASS, pos=14)
```


```{r}
library(TH.data, pos=14)
```


```{r}
library(multcomp, pos=14)
```


```{r}
library(abind, pos=19)
```


```{r}
AnovaModel.1 <- aov(temtraba ~ exposicao, data=Dataset)
```


```{r}
summary(AnovaModel.1)
```


```{r}
with(Dataset, numSummary(temtraba, groups=exposicao, statistics=c("mean", "sd")))
```


```{r}
with(Dataset, tapply(temtraba, exposicao, median, na.rm=TRUE))
```


```{r}
kruskal.test(temtraba ~ exposicao, data=Dataset)
```


```{r}
load("/home/mae5755.16/Downloads/aula11/PulsacaoUCLAD1.RData")
```


```{r}
Dataset <- within(Dataset, {
  exposicao <- as.factor(exposicao)
})
```


```{r}
with(Dataset, tapply(cvfpred, exposicao, median, na.rm=TRUE))
```


```{r}
kruskal.test(cvfpred ~ exposicao, data=Dataset)
```


```{r}
library(mvtnorm, pos=14)
```


```{r}
library(survival, pos=14)
```


```{r}
library(MASS, pos=14)
```


```{r}
library(TH.data, pos=14)
```


```{r}
library(multcomp, pos=14)
```


```{r}
library(abind, pos=19)
```


```{r}
AnovaModel.1 <- aov(temtraba ~ exposicao, data=Dataset)
```


```{r}
with(Dataset, numSummary(temtraba, groups=exposicao, statistics=c("mean", "sd")))
```


```{r}
with(Dataset, tapply(temtraba, exposicao, median, na.rm=TRUE))
```


```{r}
kruskal.test(temtraba ~ exposicao, data=Dataset)
```

```{r}
friedman.test (Pulsacao ~ Tempo | Ind, data = ColesterolUCLAD1)
```



