
load("/home/mae5755.16/Downloads/Tetrahymena.RData")
ComGlicose <- subset(Tetrahymena, subset=Glicose=='s')
ComGlicose <- subset(Tetrahymena, subset=Glicose=='S')
SemGlicose <- subset(Tetrahymena, subset=Glicose=='N')
with(ComGlicose, cor.test(Diametro, Log_concentracao, alternative="two.sided", method="pearson"))
with(ComGlicose, cor.test(Concentracao, Diametro, alternative="two.sided", method="spearman"))
with(SemGlicose, cor.test(Concentracao, Diametro, alternative="two.sided", method="spearman"))
with(SemGlicose, cor.test(Concentracao, Diametro, alternative="two.sided", method="pearson"))
with(SemGlicose, cor.test(Concentracao, Log_concentracao, alternative="two.sided", method="spearman"))
RegModel.1 <- lm(Concentracao~Glicosecat2, data=SemGlicose)
summary(RegModel.1)
RegModel.2 <- lm(Log_concentracao~Glicosecat2, data=SemGlicose)
summary(RegModel.2)
RegModel.3 <- lm(Concentracao~Log_concentracao, data=Tetrahymena)
summary(RegModel.3)
RegModel.4 <- lm(Concentracao~Glicosecat2+Log_concentracao, data=Tetrahymena)
summary(RegModel.4)

